apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: it-infra@coremaker.io
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        clouddns:
          serviceAccountSecretRef:
            name: cert-manager-secrets
            key: cert-manager-service.private-key.json
          project: {{ .Values.clouddns.projectId }}