{{- if .Values.gitRepository.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k8s-repo
  namespace: {{ .Values.gitRepository.namespace }}
spec:
  interval: {{ .Values.gitRepository.interval }}
  url: {{ .Values.gitRepository.url }}
  ref:
    branch: {{ .Values.gitRepository.branch }}
  secretRef:
    name: {{ .Values.gitRepository.secretName }}
{{- end }}