apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: {{ .Values.common.resourcesName }}
  namespace: {{.Release.Namespace}}
spec:
  interval: {{ .Values.gitRepository.interval }}
  url: {{ .Values.gitRepository.url }}
  ref:
    branch: {{ .Values.gitRepository.branch }}
  secretRef:
    name: {{ .Values.gitRepository.secretName }}